Repository jhuopensource/semesterly, pull requests merged in 2021-11, with the labels that each got.

#422 Refactor and optimize SearchBar component
  semesterly/middleware/subdomain_middleware.py
  static/js/redux/ui/search_bar.jsx
Labels: dependencies

#428 Upgrade Redux, React-Redux and refactor components
  .eslintrc.js
  package-lock.json
  package.json
  static/js/redux/__tests__/modals/__snapshots__/terms_of_service_banner_test.jsx.snap
  static/js/redux/__tests__/modals/__snapshots__/user_settings_modal_test.jsx.snap
  static/js/redux/__tests__/modals/signup_modal.test.jsx
  static/js/redux/__tests__/modals/terms_of_service_banner_test.jsx
  static/js/redux/__tests__/modals/terms_of_service_modal_test.jsx
  static/js/redux/__tests__/modals/user_acquisition_modal.test.jsx
  static/js/redux/__tests__/modals/user_settings_modal_test.jsx
  static/js/redux/__tests__/search_actions.test.jsx
  static/js/redux/actions/calendar_actions.jsx
  static/js/redux/actions/exam_actions.jsx
  static/js/redux/actions/index.jsx
  static/js/redux/actions/school_actions.jsx
  static/js/redux/actions/search_actions.jsx
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
  static/js/redux/hooks/index.jsx
  static/js/redux/init.jsx
  static/js/redux/reducers/entities_reducer.js
  static/js/redux/reducers/index.jsx
  static/js/redux/test-utils.jsx
  static/js/redux/ui/alerts/friends_in_class_alert_container.jsx
  static/js/redux/ui/containers/calendar_container.jsx
  static/js/redux/ui/containers/cell_container.jsx
  static/js/redux/ui/containers/credit_ticker_container.jsx
  static/js/redux/ui/containers/day_calendar_container.jsx
  static/js/redux/ui/containers/modals/course_modal_body_container.jsx
  static/js/redux/ui/containers/modals/course_modal_container.jsx
  static/js/redux/ui/containers/modals/exploration_modal_container.jsx
  static/js/redux/ui/containers/modals/final_exams_modal_container.jsx
  static/js/redux/ui/containers/modals/peer_modal_container.jsx
  static/js/redux/ui/containers/modals/textbook_modal_container.jsx
  static/js/redux/ui/containers/modals/user_acquisition_modal_container.jsx
  static/js/redux/ui/containers/modals/user_settings_modal_container.jsx
  static/js/redux/ui/containers/pagination_container.jsx
  static/js/redux/ui/containers/search_bar_container.jsx
  static/js/redux/ui/containers/search_side_bar_container.jsx
  static/js/redux/ui/containers/semesterly_container.jsx
  static/js/redux/ui/containers/side_bar_container.jsx
  static/js/redux/ui/containers/slot_manager_container.jsx
  static/js/redux/ui/containers/terms_of_service_modal_container.jsx
  static/js/redux/ui/containers/timetable_name_input_container.jsx
  static/js/redux/ui/containers/top_bar_container.jsx
  static/js/redux/ui/master_slot.jsx
  static/js/redux/ui/modals/user_acquisition_modal.jsx
  static/js/redux/ui/modals/user_settings_modal.jsx
  static/js/redux/ui/search_bar.jsx
  static/js/redux/ui/semesterly.jsx
  static/js/redux/ui/side_bar.jsx
  static/js/redux/ui/timetable_name_input.jsx
Labels: dependencies

#437 move autoSave dispatch to fix issues with timetable not updated
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
Labels: bug

#439 Update README with GH Actions Badge + Fix Chromedriver
  .github/workflows/semesterly.yml
  README.md
Labels: organizational
