Repository jhuopensource/semesterly, pull requests merged in 2021-12, with the labels that each got.

#441 Fix custom event
  package-lock.json
  package.json
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
  static/js/redux/init.jsx
  static/js/redux/ui/containers/semesterly_container.jsx
  static/js/redux/ui/slot_manager.jsx
Labels: bug

#464 Add backend branch to automated tests
  .github/workflows/semesterly.yml
Labels: python

#463 Refactor Authpipe
  Dockerfile
  authpipe/__init__.py
  authpipe/apps.py
  authpipe/tests.py
  authpipe/urls.py
  authpipe/utils.py
  authpipe/views.py
  docs/index.rst
  docs/styleguide.rst
  helpers/test/utils.py
  requirements.txt
  student/migrations/0035_alter_student_jhed.py
  student/models.py
Labels: python

#466 Attempt to Activate GH Actions
  .github/workflows/semesterly.yml
Labels: bug

#472 Delete exams
  analytics/migrations/0020_delete_finalexammodalview.py
  analytics/models.py
  analytics/templates/analytics_dashboard.html
  analytics/urls.py
  analytics/views.py
  docs/documentation.rst
  docs/howitworks.rst
  docs/modules/exams.rst
  exams/__init__.py
  exams/admin.py
  exams/apps.py
  exams/final_exam_scheduler.py
  exams/jhu_final_exam_scheduler.py
  exams/migrations/0001_initial.py
  exams/migrations/__init__.py
  exams/models.py
  exams/tests.py
  exams/urls.py
  exams/views.py
  semesterly/settings.py
  semesterly/urls.py
Labels: python

#470 Delete pilot app
  pilot/__init__.py
  pilot/admin.py
  pilot/apps.py
  pilot/forms.py
  pilot/migrations/__init__.py
  pilot/models.py
  pilot/static/css/pilot_main.css
  pilot/static/fonts/panquin.woff2
  pilot/static/pilotLogo.png
  pilot/templates/pilot/base.html
  pilot/templates/pilot/courses.html
  pilot/templates/pilot/get_info.html
  pilot/templates/pilot/meetings.html
  pilot/templates/pilot/offerings.html
  pilot/templates/pilot/student_info.html
  pilot/templates/pilot/welcome.html
  pilot/tests.py
  pilot/urls.py
  pilot/views.py
  semesterly/settings.py
  semesterly/urls.py
  student/migrations/0036_delete_pilotoffering.py
  student/models.py
Labels: python

#473 Delete frontend pilot code
  static/css/timetable/framework/page_layout.scss
  static/css/timetable/partials/search_bar.scss
  static/css/timetable/partials/social.scss
  static/js/redux/ui/calendar.jsx
  static/js/redux/ui/modals/course_modal_body.jsx
  static/js/redux/ui/search_result.jsx
Labels: javascript

#475 Remove frontend exam code
  static/js/redux/__tests__/selectors.test.jsx
  static/js/redux/actions/exam_actions.jsx
  static/js/redux/actions/index.jsx
  static/js/redux/actions/modal_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/constants/endpoints.jsx
  static/js/redux/init.jsx
  static/js/redux/reducers/final_exams_modal_reducer.jsx
  static/js/redux/reducers/index.jsx
  static/js/redux/reducers/semester_reducer.jsx
  static/js/redux/ui/containers/modals/final_exams_modal_container.jsx
  static/js/redux/ui/containers/modals/tut_modal_container.jsx
  static/js/redux/ui/containers/side_bar_container.jsx
  static/js/redux/ui/modals/final_exams_modal.jsx
  static/js/redux/ui/modals/tut_modal.jsx
  static/js/redux/ui/semesterly.jsx
  static/js/redux/ui/side_bar.jsx
  static/js/redux/util.jsx
Labels: javascript

#474 Refactor courses
  build/semesterly-base/requirements_base.txt
  courses/apps.py
  courses/serializers.py
  courses/tests.py
  courses/urls.py
  courses/utils.py
  courses/views.py
  requirements.txt
  timetable/templates/course_page.html
Labels: python

#476 Refactor searches
  searches/apps.py
  searches/tasks.py
  searches/tests.py
  searches/urls.py
  searches/utils.py
  searches/views.py
  timetable/models.py
Labels: python

#479 Refactor Semesterly Base Project Directory
  build/semesterly-base/requirements_base.txt
  requirements.txt
  semesterly/celery_conf.py
  semesterly/dev_credentials.py
  semesterly/middleware/middleware.py
  semesterly/middleware/subdomain_middleware.py
  semesterly/settings.py
  semesterly/test_utils.py
  semesterly/tests.py
  semesterly/urls.py
  semesterly/views.py
  semesterly/wsgi.py
Labels: python

#481 Add yml for black, python autoformatter
  .github/workflows/black.yml
Labels: python

#483 Change PersonalTimetable <-> PersonalEvent many-to-many relationship to PersonalEvent -> PersonalTimetable foreign key relationship
  student/migrations/0037_personalevent_timetable.py
  student/migrations/0038_change_pe_to_fk.py
  student/migrations/0039_remove_personaltimetable_events.py
  student/models.py
Labels: python

#482 Refactor redux course info
  .github/workflows/semesterly.yml
  static/js/redux/actions/initActions.js
  static/js/redux/actions/modal_actions.jsx
  static/js/redux/actions/search_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/constants/commonTypes.ts
  static/js/redux/init.jsx
  static/js/redux/state/calendar_reducer.jsx
  static/js/redux/state/course_info_reducer.jsx
  static/js/redux/state/entities_reducer.js
  static/js/redux/state/exploration_modal_reducer.jsx
  static/js/redux/state/index.jsx
  static/js/redux/state/search_results_reducer.jsx
  static/js/redux/state/slices/courseInfoSlice.ts
  static/js/redux/state/slices/index.ts
  static/js/redux/state/slices/userInfoSlice.ts
  static/js/redux/ui/containers/modals/course_modal_container.jsx
Labels: ui/ux, javascript

#493 Refactor redux timetables
  static/js/redux/__tests__/semester_reducer.test.jsx
  static/js/redux/actions/initActions.js
  static/js/redux/actions/search_actions.jsx
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/constants/commonTypes.ts
  static/js/redux/init.jsx
  static/js/redux/state/entities_reducer.js
  static/js/redux/state/index.jsx
  static/js/redux/state/saving_timetable_reducer.jsx
  static/js/redux/state/semester_reducer.jsx
  static/js/redux/state/slices/calendarSlice.ts
  static/js/redux/state/slices/timetablesSlice.ts
  static/js/redux/state/timetables_reducer.jsx
  static/js/redux/state/ui_reducer.jsx
  static/js/redux/ui/containers/modals/course_modal_body_container.jsx
  static/js/redux/ui/containers/modals/course_modal_container.jsx
  static/js/redux/ui/containers/modals/exploration_modal_container.jsx
  static/js/redux/ui/containers/search_side_bar_container.jsx
  static/js/redux/ui/modals/course_modal_body.jsx
  static/js/redux/ui/search_side_bar.jsx
Labels: javascript
