Repository jhuopensource/semesterly, pull requests merged in 2022-02, with the labels that each got.

#623 Disable FB Login
  static/js/redux/ui/modals/user_acquisition_modal.jsx
Labels: bug, temporary-patch

#627 Block 2nd FB Button
  static/js/redux/ui/modals/user_settings_modal.jsx
Labels: temporary-patch

#629 Docs/onboarding
  dev/hacksessions.md
  dev/onboarding.md
Labels: docs

#631 Docs: Add additional missing instructions in projects.md
  dev/projects.md
Labels: docs

#622 Refactor/more redux reducers
  static/js/redux/__tests__/modals/terms_of_service_banner.test.jsx
  static/js/redux/__tests__/modals/terms_of_service_modal.test.jsx
  static/js/redux/__tests__/semester_reducer.test.jsx
  static/js/redux/actions/calendar_actions.jsx
  static/js/redux/actions/initActions.js
  static/js/redux/actions/modal_actions.jsx
  static/js/redux/actions/search_actions.jsx
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/constants/commonTypes.ts
  static/js/redux/init.jsx
  static/js/redux/state/index.tsx
  static/js/redux/state/preference_modal_reducer.jsx
  static/js/redux/state/preferences_reducer.jsx
  static/js/redux/state/registrar_reducer.jsx
  static/js/redux/state/save_calendar_modal_reducer.jsx
  static/js/redux/state/school_reducer.jsx
  static/js/redux/state/search_results_reducer.jsx
  static/js/redux/state/semester_reducer.jsx
  static/js/redux/state/slices/customEventsSlice.ts
  static/js/redux/state/slices/preferencesSlice.ts
  static/js/redux/state/slices/registrarSlice.ts
  static/js/redux/state/slices/saveCalendarModalSlice.ts
  static/js/redux/state/slices/schoolSlice.ts
  static/js/redux/state/slices/searchResultsSlice.ts
  static/js/redux/state/slices/semesterSlice.ts
  static/js/redux/state/slices/termOfServiceBannerSlice.ts
  static/js/redux/state/slices/termsOfServiceModalSlice.ts
  static/js/redux/state/slices/uiSlice.ts
  static/js/redux/state/terms_of_service_banner_reducer.jsx
  static/js/redux/state/terms_of_service_modal_reducer.jsx
  static/js/redux/state/ui_reducer.jsx
  static/js/redux/ui/alerts/conflict_alert_container.jsx
  static/js/redux/ui/containers/calendar_container.jsx
  static/js/redux/ui/containers/day_calendar_container.jsx
  static/js/redux/ui/containers/modals/preference_modal_container.jsx
  static/js/redux/ui/containers/modals/save_calendar_modal_container.jsx
  static/js/redux/ui/containers/search_bar_container.jsx
  static/js/redux/ui/containers/sort_menu_container.jsx
  static/js/redux/ui/containers/terms_of_service_banner_container.jsx
  static/js/redux/ui/containers/terms_of_service_modal_container.jsx
  static/js/redux/ui/day_calendar.jsx
  static/js/redux/ui/modals/preference_modal.jsx
  static/js/redux/ui/sort_menu.jsx
  static/js/redux/ui/terms_of_service_banner.jsx
Labels: javascript

#632 PR Template: Add change log
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#657 Unblock FB Buttons
  README.md
  semesterly/templates/about.html
  static/js/redux/ui/modals/user_acquisition_modal.jsx
  static/js/redux/ui/modals/user_settings_modal.jsx
  timetable/templates/header.html
  timetable/templates/index.html
  timetable/templates/profile.html
Labels: organizational

#659 Refactor/more reducers
  package-lock.json
  package.json
  static/js/redux/__tests__/schema.test.js
  static/js/redux/__tests__/selectors.test.jsx
  static/js/redux/actions/calendar_actions.jsx
  static/js/redux/actions/modal_actions.jsx
  static/js/redux/actions/search_actions.jsx
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/constants/commonTypes.ts
  static/js/redux/init.jsx
  static/js/redux/state/entities_reducer.js
  static/js/redux/state/feature_request_modal_reducer.jsx
  static/js/redux/state/friends_reducer.jsx
  static/js/redux/state/index.tsx
  static/js/redux/state/integration_modal_reducer.jsx
  static/js/redux/state/integrations_reducer.jsx
  static/js/redux/state/notification_token_reducer.jsx
  static/js/redux/state/optional_courses_reducer.jsx
  static/js/redux/state/peer_modal_reducer.jsx
  static/js/redux/state/slices/courseInfoSlice.ts
  static/js/redux/state/slices/entitiesSlice.ts
  static/js/redux/state/slices/friendsSlice.ts
  static/js/redux/state/slices/integrationModalSlice.ts
  static/js/redux/state/slices/notificationTokenSlice.ts
  static/js/redux/state/slices/optionalCoursesSlice.ts
  static/js/redux/state/slices/peerModalSlice.ts
  static/js/redux/state/slices/preferencesSlice.ts
  static/js/redux/state/slices/uiSlice.ts
  static/js/redux/ui/containers/modals/course_modal_body_container.jsx
  static/js/redux/ui/containers/modals/exploration_modal_container.jsx
  static/js/redux/ui/containers/modals/integration_modal_container.jsx
  static/js/redux/ui/containers/modals/peer_modal_container.jsx
  static/js/redux/ui/containers/search_side_bar_container.jsx
  static/js/redux/ui/containers/side_bar_container.jsx
  static/js/redux/ui/modals/exploration_modal.jsx
  static/js/redux/ui/modals/integration_modal.jsx
  static/js/redux/ui/search_result.jsx
  static/js/redux/ui/side_bar.jsx
Labels: javascript

#675 Docs/setup: Emphasize appending to the host file, so new members know not to replace localhost
  docs/setup.rst
Labels: docs

#676 Replace Docs Links in README
  README.md
  timetable/templates/index.html
Labels: docs

#681 Refactor advanced search
  static/js/redux/state/slices/entitiesSlice.ts
  static/js/redux/ui/containers/modals/course_modal_body_container.jsx
  static/js/redux/ui/containers/modals/exploration_modal_container.jsx
  static/js/redux/ui/modals/advanced_search_modal.tsx
  static/js/redux/ui/modals/exploration_modal.jsx
  static/js/redux/ui/semesterly.jsx
Labels: javascript

#687 Press: Cached images for press page
  semesterly/templates/press.html
  static/img/press_img/classroom-press.jpeg
  static/img/press_img/hub-press.jpeg
  static/img/press_img/newsletter-press.png
  static/img/press_img/nlonthedl-press.png
  static/img/press_img/noah-press.jpeg
  static/img/press_img/odyssey-press-1.jpeg
  static/img/press_img/odyssey-press.jpeg
Labels: ui/ux

#694 Feature: Paginate advanced search
  .eslintrc.js
  package-lock.json
  package.json
  searches/tests.py
  searches/views.py
  static/js/redux/actions/initActions.js
  static/js/redux/actions/search_actions.jsx
  static/js/redux/constants/endpoints.jsx
  static/js/redux/state/slices/entitiesSlice.ts
  static/js/redux/state/slices/explorationModalSlice.ts
  static/js/redux/ui/modals/advanced_search_modal.tsx
Labels: ui/ux
