Repository jhuopensource/semesterly, pull requests merged in 2022-01, with the labels that each got.

#496 Remove textbook frontend code
  static/css/timetable/main.scss
  static/css/timetable/modules/textbooks.scss
  static/css/timetable/partials/final_exam_modal.scss
  static/css/timetable/partials/side_bar.scss
  static/css/timetable/partials/textbook_modal.scss
  static/js/redux/__fixtures__/course_modal_body.fixture.jsx
  static/js/redux/actions/modal_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/constants/commonTypes.ts
  static/js/redux/constants/semesterlyPropTypes.jsx
  static/js/redux/init.jsx
  static/js/redux/state/entities_reducer.js
  static/js/redux/state/index.jsx
  static/js/redux/state/textbook_modal_reducer.jsx
  static/js/redux/ui/containers/modals/textbook_modal_container.jsx
  static/js/redux/ui/containers/modals/tut_modal_container.jsx
  static/js/redux/ui/containers/side_bar_container.jsx
  static/js/redux/ui/modals/course_modal_body.jsx
  static/js/redux/ui/modals/textbook_modal.jsx
  static/js/redux/ui/modals/tut_modal.jsx
  static/js/redux/ui/semesterly.jsx
  static/js/redux/ui/side_bar.jsx
  static/js/redux/ui/textbook.jsx
Labels: ui/ux, javascript

#497 Refactor redux custom slots
  static/js/redux/actions/initActions.js
  static/js/redux/actions/timetable_actions.jsx
  static/js/redux/actions/user_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/state/custom_slots_reducer.jsx
  static/js/redux/state/index.jsx
  static/js/redux/state/saving_timetable_reducer.jsx
  static/js/redux/state/slices/customEventsSlice.ts
  static/js/redux/ui/containers/slot_manager_container.jsx
Labels: javascript

#501 Refactor classmates reducer
  static/js/redux/actions/user_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/state/classmates_reducer.jsx
  static/js/redux/state/index.jsx
  static/js/redux/state/slices/classmatesSlice.ts
  student/views.py
Labels: javascript

#528 Refactor redux exploration modal
  static/js/redux/actions/initActions.js
  static/js/redux/actions/modal_actions.jsx
  static/js/redux/actions/school_actions.jsx
  static/js/redux/actions/search_actions.jsx
  static/js/redux/constants/actionTypes.jsx
  static/js/redux/state/entities_reducer.js
  static/js/redux/state/exploration_modal_reducer.jsx
  static/js/redux/state/index.jsx
  static/js/redux/state/school_reducer.jsx
  static/js/redux/state/slices/explorationModalSlice.ts
  static/js/redux/state/slices/index.ts
  static/js/redux/ui/containers/modals/exploration_modal_container.jsx
  static/js/redux/ui/containers/search_bar_container.jsx
  static/js/redux/ui/search_bar.jsx
Labels: javascript

#532 Refactor calendar component
  .eslintrc.js
  package-lock.json
  package.json
  static/js/redux/ui/calendar.jsx
  static/js/redux/ui/calendar.tsx
Labels: javascript

#585 fix-prop-types: remove page from exploration modal
  static/js/redux/ui/modals/exploration_modal.jsx
  static/js/redux/ui/modals/peer_modal.jsx
Labels: javascript

#590 Custom event:add back migration file for color and location
  student/migrations/0041_auto_20220118_2013.py
  student/models.py
  student/views.py
Labels: python

#592 Feature/custom event rename credit
  student/migrations/0041_auto_20220119_1546.py
  student/models.py
  student/views.py
Labels: python

#612 Feature/enhance advanced search
  package-lock.json
  package.json
  static/css/timetable/partials/exploration_modal.scss
  static/css/timetable/vendor/react_input_range.scss
  static/js/redux/actions/calendar_actions.jsx
  static/js/redux/constants/endpoints.jsx
  static/js/redux/ui/advanced_search_filters.jsx
  static/js/redux/ui/calendar.tsx
  static/js/redux/ui/master_slot.jsx
  static/js/redux/ui/modals/exploration_modal.jsx
  static/js/redux/ui/time_selector.jsx
Labels: ui/ux, javascript

#364 uCredit Advertisements
  semesterly/templates/press.html
  semesterly/templates/ucredit.html
  static/css/splash.css
  static/css/student/profile.css
  static/img/press_img/jhu-cs-recognition.png
  static/img/updates/ucredit-logo.png
  timetable/templates/index.html
Labels: organizational, medium-priority

#617 Feature/jhed login show preferred name
  authpipe/utils.py
  static/css/timetable/partials/user_settings_modal.scss
  static/js/redux/state/slices/userInfoSlice.ts
  static/js/redux/ui/modals/user_settings_modal.jsx
  student/migrations/0042_student_preferred_name.py
  student/models.py
  student/serializers.py
  student/views.py
  timetable/templates/profile.html
Labels: ui/ux
